// <auto-generated />
using System;
using ArenaOps.CoreService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaOps.CoreService.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260219082748_InitialCoreSchema")]
    partial class InitialCoreSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Landmark", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<Guid>("SeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("FeatureId");

                    b.HasIndex("SeatingPlanId");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsAccessible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<string>("RowLabel")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SeatLabel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeatId");

                    b.HasIndex("SectionId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.SeatingPlan", b =>
                {
                    b.Property<Guid>("SeatingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeatingPlanId");

                    b.HasIndex("StadiumId");

                    b.ToTable("SeatingPlans");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<string>("SeatType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SectionId");

                    b.HasIndex("SeatingPlanId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Stadium", b =>
                {
                    b.Property<Guid>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StadiumId");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Landmark", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.SeatingPlan", "SeatingPlan")
                        .WithMany("Landmarks")
                        .HasForeignKey("SeatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatingPlan");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Seat", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Section", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.SeatingPlan", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Stadium", "Stadium")
                        .WithMany("SeatingPlans")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Section", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.SeatingPlan", "SeatingPlan")
                        .WithMany("Sections")
                        .HasForeignKey("SeatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatingPlan");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.SeatingPlan", b =>
                {
                    b.Navigation("Landmarks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Section", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Stadium", b =>
                {
                    b.Navigation("SeatingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
