// <auto-generated />
using System;
using ArenaOps.CoreService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArenaOps.CoreService.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    [Migration("20260304045032_MergeSync")]
    partial class MergeSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("StadiumId");

                    b.HasIndex("Status");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventLandmark", b =>
                {
                    b.Property<Guid>("EventLandmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("EventSeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<Guid?>("SourceFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("EventLandmarkId");

                    b.HasIndex("EventSeatingPlanId");

                    b.HasIndex("SourceFeatureId");

                    b.ToTable("EventLandmarks");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventSeatingPlan", b =>
                {
                    b.Property<Guid>("EventSeatingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SourceSeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventSeatingPlanId");

                    b.HasIndex("EventId");

                    b.HasIndex("SourceSeatingPlanId");

                    b.ToTable("EventSeatingPlans");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventSection", b =>
                {
                    b.Property<Guid>("EventSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("EventSeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<string>("SeatType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("SourceSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EventSectionId");

                    b.HasIndex("EventSeatingPlanId");

                    b.HasIndex("SourceSectionId");

                    b.ToTable("EventSections");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Landmark", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<Guid>("SeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("FeatureId");

                    b.HasIndex("SeatingPlanId");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("IsAccessible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<string>("RowLabel")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SeatLabel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeatId");

                    b.HasIndex("RowLabel");

                    b.HasIndex("SectionId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.SeatingPlan", b =>
                {
                    b.Property<Guid>("SeatingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StadiumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeatingPlanId");

                    b.HasIndex("StadiumId");

                    b.ToTable("SeatingPlans");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PosX")
                        .HasColumnType("float");

                    b.Property<double>("PosY")
                        .HasColumnType("float");

                    b.Property<string>("SeatType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SeatingPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SectionId");

                    b.HasIndex("SeatingPlanId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Stadium", b =>
                {
                    b.Property<Guid>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StadiumId");

                    b.HasIndex("City");

                    b.HasIndex("OwnerId");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.TicketType", b =>
                {
                    b.Property<Guid>("TicketTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SalePLU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketTypeId");

                    b.HasIndex("EventId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Event", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventLandmark", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.EventSeatingPlan", "EventSeatingPlan")
                        .WithMany("EventLandmarks")
                        .HasForeignKey("EventSeatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Landmark", "SourceLandmark")
                        .WithMany()
                        .HasForeignKey("SourceFeatureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventSeatingPlan");

                    b.Navigation("SourceLandmark");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventSeatingPlan", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.SeatingPlan", "SourceSeatingPlan")
                        .WithMany()
                        .HasForeignKey("SourceSeatingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceSeatingPlan");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventSection", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.EventSeatingPlan", "EventSeatingPlan")
                        .WithMany("EventSections")
                        .HasForeignKey("EventSeatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Section", "SourceSection")
                        .WithMany()
                        .HasForeignKey("SourceSectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EventSeatingPlan");

                    b.Navigation("SourceSection");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Landmark", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.SeatingPlan", "SeatingPlan")
                        .WithMany("Landmarks")
                        .HasForeignKey("SeatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatingPlan");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Seat", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Section", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.SeatingPlan", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.Stadium", "Stadium")
                        .WithMany("SeatingPlans")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Section", b =>
                {
                    b.HasOne("ArenaOps.CoreService.Domain.Entities.SeatingPlan", "SeatingPlan")
                        .WithMany("Sections")
                        .HasForeignKey("SeatingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatingPlan");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.EventSeatingPlan", b =>
                {
                    b.Navigation("EventLandmarks");

                    b.Navigation("EventSections");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.SeatingPlan", b =>
                {
                    b.Navigation("Landmarks");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Section", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("ArenaOps.CoreService.Domain.Entities.Stadium", b =>
                {
                    b.Navigation("SeatingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
